name: color_picker_example
description: A color_picker example Flutter project.
version: 1.0.0+1

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  color_picker:
    path: ../

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true

environment:
  sdk: ">=3.3.0 <4.0.0"
