name: color_pickr_example
description: A color_pickr example Flutter project.
version: 1.0.0+1

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  color_pickr:
    path: ../

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true

environment:
  sdk: ">=3.3.0 <4.0.0"
