name: color_pickr
description: HSV(HSB)/HSL/RGB/Material color picker inspired by all the good design for your amazing flutter apps.
version: 1.0.0+2
homepage: https://github.com/YawarOsman/color_pickr
issue_tracker: https://github.com/YawarOsman/color_pickr/issues


environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
